---
- name: Verify
  hosts: all
  gather_facts: false
  vars:
    stern_bin_path: "/usr/local/bin"
    stern_version: "version: 1.20.1"
  tasks:
    - name: Ensure Stern is installed.
      stat:
        path: "{{ stern_bin_path }}/stern"
      register: this_stat

    - name: Get version from Stern.
      command: "{{ stern_bin_path }}/stern --version"
      register: this_exec

    - assert:
        that:
          - this_stat.stat.exists

    - assert:
        that:
          - this_exec.stdout_lines[0] == stern_version
